### ISSUE TITLE
What is the lastest version and not see media type: VideoOnly ?

### ISSUE THREAD

**Issue by cryinrain69** [olxgroup-oss/media-picker-android#10]
Hi.
I tried `implementation 'com.github.olxgroup-oss: media-picker-android: 0.0.3_dev' `but found no needToShowCover () function in `setUpGallery`.
In the source code downloaded from github, there are them.
Beside, I can't see media type: **VideoOnly**
Please check again.
Thank you so much.

**Comment by bharatghimire005** [comment]
Hi Please use `implementation` 'com.github.olxgroup-oss:media-picker-android:1.0.0-alpha01' version.
Currently, we are supporting  **VideoOnly**  media type. We will try to update it in upcoming version.
